name: 'Appcenter Distribute - Github Actions'
author: 'John Matthews'
description: 'Wraps the appcenter CLI to enable common commands.  Forked and fixed with latest npm and a file checker.'
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile'
